### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by elkinaguas**

### CODE REVIEW

**Comment by evgeni** [comment]
The files in this repo are generated.

Please submit a PR against https://github.com/theforeman/foreman/blob/874c0d9227cf3d77133c93f1a4bf672f485dd674/app/controllers/api/v2/ptables_controller.rb#L55

**Review by ekohl — CHANGES_REQUESTED** [review]
I think you're correct, but these files are generated. Would you mind submitting a PR to the source where it's generated from? That's here:
https://github.com/theforeman/foreman/blob/874c0d9227cf3d77133c93f1a4bf672f485dd674/app/controllers/api/v2/ptables_controller.rb#L55

**Comment by elkinaguas** [comment]
Sure, I will change the right file.

**Comment by ekohl** [comment]
@elkinaguas did you manage to open the PR? Let us know if you ran into any problems. Otherwise it's nice to link it back here.

**Comment by elkinaguas** [comment]
Hi @ekohl, I did, but there is a modification I need to do. Apparently, I also need to create an issue in https://projects.theforeman.org/projects/foreman/issues for the typo (I thought a typo was a minor issue so I didn't do it before). I haven't had time to create the issue, so I'll do it tomorrow.

I'll link the PR here once I apply the changes requested.

**Comment by elkinaguas** [comment]
Here is the PR that will fix the typo https://github.com/theforeman/foreman/pull/9457.

Modifications where required but I responded saying I don't think they are necessary. I'm waiting for the person who requested the changes to respond or resolve the conversation.

**Pull request closed without merging**
